# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]     # or your default branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the source code
      - uses: actions/checkout@v3

      # 2) Set up the specific JDK version
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # 3) Build and test with Maven
      - name: Build with Maven
        run: mvn clean install
